src/main/java/com/homeadvisor/kafdrop/model/ConsumerTopicVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;

public class ConsumerTopicVO
{
   private final String topic;
   private final Map<Integer, ConsumerPartitionVO> offsets = new TreeMap<>();

   public ConsumerTopicVO(String topic)
   {
      this.topic = topic;
   }

   public String getTopic()
   {
      return topic;
   }

   public void addOffset(ConsumerPartitionVO offset)
   {
      offsets.put(offset.getPartitionId(), offset);
   }

   public long getLag()
   {
      return offsets.values().stream()
         .map(ConsumerPartitionVO::getLag)
         .filter(lag -> lag >= 0)
         .reduce(0L, Long::sum);
   }

   public long getMaxLag()
   {
      return offsets.values().stream()
         .map(ConsumerPartitionVO::getLag)
         .filter(lag -> lag >= 0)
         .reduce(0L, Long::max);
   }

   public Collection<ConsumerPartitionVO> getPartitions()
   {
      return offsets.values();
   }

   public double getCoveragePercent()
   {
      return (offsets.size() > 0) ? ((double)getAssignedPartitionCount()) / offsets.size() : 0.0;
   }

   public int getAssignedPartitionCount()
   {
      return (int) offsets.values().stream()
         .filter(p -> p.getOwner() != null)
         .count();
   }

   public int getOwnerCount()
   {
      return (int)offsets.values().stream()
         .map(ConsumerPartitionVO::getOwner)
         .filter(Objects::nonNull)
         .distinct()
         .count();
   }
}

src/main/java/com/homeadvisor/kafdrop/model/ConsumerVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import org.apache.commons.lang.Validate;

import java.util.*;
import java.util.stream.Collectors;

public class ConsumerVO implements Comparable<ConsumerVO>
{
   private String groupId;
   private Map<String, ConsumerTopicVO> topics = new TreeMap<>();
   private List<ConsumerRegistrationVO> activeInstances = new ArrayList<>();

   public ConsumerVO(String groupId)
   {
      Validate.notEmpty("groupId is required");
      this.groupId = groupId;
   }

   public String getGroupId()
   {
      return groupId;
   }

   public void setGroupId(String groupId)
   {
      this.groupId = groupId;
   }

   public void addActiveInstance(ConsumerRegistrationVO id)
   {
      activeInstances.add(id);
   }

   public List<ConsumerRegistrationVO> getActiveInstances()
   {
      return activeInstances;
   }

   public List<ConsumerRegistrationVO> getActiveInstancesForTopic(String topic)
   {
      return activeInstances.stream()
         .filter(reg -> reg.getSubscriptions().containsKey(topic))
         .collect(Collectors.toList());
   }

   public void addTopic(ConsumerTopicVO topic)
   {
      topics.put(topic.getTopic(), topic);
   }

   public ConsumerTopicVO getTopic(String topic)
   {
      return topics.get(topic);
   }

   public Collection<ConsumerTopicVO> getTopics()
   {
      return topics.values();
   }

   public int getActiveTopicCount()
   {
      return topics.values().stream()
         .map(t -> t.getAssignedPartitionCount() > 0 ? 1 : 0)
         .reduce(0, Integer::sum);
   }

   @Override
   public int compareTo(ConsumerVO that)
   {
      return this.groupId.compareTo(that.groupId);
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      ConsumerVO vo = (ConsumerVO) o;

      if (!groupId.equals(vo.groupId)) return false;

      return true;
   }

   @Override
   public int hashCode()
   {
      return groupId.hashCode();
   }

}

src/main/java/com/homeadvisor/kafdrop/model/TopicVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import java.util.*;
import java.util.stream.Collectors;

public class TopicVO implements Comparable<TopicVO>
{
   private String name;
   private Map<Integer, TopicPartitionVO> partitions = new TreeMap<>();
   private Map<String, Object> config = new TreeMap<>();
   // description?
   // partition state
   // delete supported?


   public TopicVO(String name)
   {
      this.name = name;
   }

   public String getName()
   {
      return name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public Map<String, Object> getConfig()
   {
      return config;
   }

   public void setConfig(Map<String, Object> config)
   {
      this.config = config;
   }

   public Collection<TopicPartitionVO> getPartitions()
   {
      return partitions.values();
   }

   public Optional<TopicPartitionVO> getPartition(int partitionId)
   {
      return Optional.ofNullable(partitions.get(partitionId));
   }

   public Collection<TopicPartitionVO> getLeaderPartitions(int brokerId)
   {
      return partitions.values().stream()
         .filter(tp -> tp.getLeader() != null && tp.getLeader().getId() == brokerId)
         .collect(Collectors.toList());
   }

   public Collection<TopicPartitionVO> getUnderReplicatedPartitions()
   {
      return partitions.values().stream()
         .filter(TopicPartitionVO::isUnderReplicated)
         .collect(Collectors.toList());
   }

   public void setPartitions(Map<Integer, TopicPartitionVO> partitions)
   {
      this.partitions = partitions;
   }

   /**
    * Returns the total number of messages published to the topic, ever
    * @return
    */
   public long getTotalSize()
   {
      return partitions.values().stream()
         .map(TopicPartitionVO::getSize)
         .reduce(0L, Long::sum);
   }

   /**
    * Returns the total number of messages available to consume from the topic.
    * @return
    */
   public long getAvailableSize()
   {
      return partitions.values().stream()
         .map(p -> p.getSize() - p.getFirstOffset())
         .reduce(0L, Long::sum);
   }

   public double getPreferredReplicaPercent()
   {
      long preferredLeaderCount = partitions.values().stream()
         .filter(TopicPartitionVO::isLeaderPreferred)
         .count();
      return ((double) preferredLeaderCount) / ((double)partitions.size());
   }

   public void addPartition(TopicPartitionVO partition)
   {
      partitions.put(partition.getId(), partition);
   }

   @Override
   public int compareTo(TopicVO that)
   {
      return this.name.compareTo(that.name);
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      TopicVO that = (TopicVO) o;

      if (!name.equals(that.name)) return false;

      return true;
   }

   @Override
   public int hashCode()
   {
      return name.hashCode();
   }

}

src/main/resources/templates/broker-detail.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Broker: ${broker.id?string}">
<style type="text/css">
    .bs-table.overview td { white-space: nowrap; }

    td.leader-partitions { word-break: break-all; }

</style>
</@template.header>

<#setting number_format="0">

<h1>Broker Id: ${broker.id}</h1>

<div id="topic-overview">
    <h2>Broker Overview</h2>

    <table class="table table-bordered overview">
        <tbody>
        <tr>
            <td><i class="fa fa-laptop"></i> Host</td>
            <td>${broker.host}:${broker.port}</td>
        </tr>
        <tr>
            <td><i class="fa fa-clock-o"></i> Start Time</td>
            <td>${broker.timestamp?string["yyyy-MM-dd HH:mm:ss.SSSZ"]}</td>
        </tr>
        <tr>
            <td>Controller</td>
            <td><@template.yn broker.controller/></td>
        </tr>
        <tr>
            <td># of Topics</td>
            <td>${topics?size}</td>
        </tr>

        <#assign partitionCount=0>
        <#list topics as t>
            <#assign partitionCount=partitionCount+(t.getLeaderPartitions(broker.id)?size)>
        </#list>
        <tr>
            <td># of Partitions</td>
            <td>${partitionCount}</td>
        </tr>
        </tbody>
    </table>
</div>

<div>
    <h2>Topic Detail</h2>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Topic</th>
            <th>Total Partitions</th>
            <th>Broker Partitions</th>
            <th>Partition Ids</th>
        </tr>
        </thead>
        <tbody>
        <#list topics as t>
              <tr>
                  <td><a href="/topic/${t.name}">${t.name}</a></td>
                  <td>${t.partitions?size}</td>
                  <td>${t.getLeaderPartitions(broker.id)?size}</td>
                  <td class="leader-partitions"><#list t.getLeaderPartitions(broker.id) as p>${p.id}<#sep>,</#list></td>
              </tr>
        </#list>
        </tbody>
    </table>
</div>

<@template.footer/>

src/main/resources/templates/cluster-overview.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Broker List"/>

<script src="/js/powerFilter.js"></script>



<#setting number_format="0">
    <div>
        <h2>Kafka Cluster Overview</h2>

        <div id="cluster-overview">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td>Zookeeper Host Configuration</td>
                    <td><#list zookeeper.connectList as z>${z}<#if z_has_next>, </#if></#list></td>
                </tr>
                <tr>
                    <td>Total Topics</td>
                    <td>${clusterSummary.topicCount}</td>
                </tr>
                <tr>
                    <td>Total Partitions</td>
                    <td>${clusterSummary.partitionCount}</td>
                </tr>
                <tr>
                    <td>Total Preferred Partition Leader</td>
                    <td <#if clusterSummary.preferredReplicaPercent lt 1.0>class="warning"</#if>>${clusterSummary.preferredReplicaPercent?string.percent}</td>
                </tr>
                <tr>
                    <td>Total Under Replicated Partitions</td>
                    <td <#if clusterSummary.underReplicatedCount gt 0>class="warning"</#if>>${clusterSummary.underReplicatedCount}</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div id="brokers">
            <h3>Brokers</h3>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Host</th>
                    <th>Port</th>
                    <th>JMX Port</th>
                    <th>Version</th>
                    <th>
                        Start Time
                        <a title="Time the broker joined the cluster"
                           data-toggle="tooltip" data-placement="top" href="#"
                        ><i class="fa fa-question-circle"></i></a>
                    </th>
                    <th>Controller?</th>
                    <th>
                        # Partitions (% of Total)
                        <a title="# of partitions this broker is the leader for"
                           data-toggle="tooltip" data-placement="top" href="#"
                        ><i class="fa fa-question-circle"></i></a>
                    </th>
                </tr>
                </thead>
                <tbody>
                <#if brokers?size == 0>
                    <tr>
                        <td class="danger text-danger" colspan="8"><i class="fa fa-warning"></i> No brokers available</td>
                    </tr>
                <#elseif missingBrokerIds?size gt 0>
                    <tr>
                        <td class="danger text-danger" colspan="8"><i class="fa fa-warning"></i> Missing brokers: <#list missingBrokerIds as b>${b}<#if b_has_next>, </#if></#list></td>
                    </tr>
                </#if>
                <#list brokers as b>
                <tr>
                    <td><a href="/broker/${b.id}"><i class="fa fa-info-circle fa-lg"></i> ${b.id}</a></td>
                    <td>${b.host}</td>
                    <td>${b.port?string}</td>
                    <td>${b.jmxPort?string}</td>
                    <td>${b.version}</td>
                    <td>${b.timestamp?string["yyyy-MM-dd HH:mm:ss.SSSZ"]}</td>
                    <td><@template.yn b.controller/></td>
                    <td>${(clusterSummary.getBrokerLeaderPartitionCount(b.id))!0} (${(((clusterSummary.getBrokerLeaderPartitionCount(b.id))!0)/clusterSummary.partitionCount)?string.percent})</td>
                </tr>
                </#list>
                </tbody>
            </table>
        </div>

        <div id="topics">
            <h3>Topics</h3>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>
                        Name

                        <span style="font-weight:normal;">
                            &nbsp;<INPUT id='filter' size=25 NAME='searchRow' title='Just type to filter the rows'>&nbsp;
                            <span id="rowCount"></span>
                        </span>
                    </th>
                    <th>
                        Partitions
                        <a title="Number of partitions in the topic"
                           data-toggle="tooltip" data-placement="top" href="#"
                        ><i class="fa fa-question-circle"></i></a>
                    </th>
                    <th>
                        % Preferred
                        <a title="Percent of partitions where the preferred broker has been assigned leadership"
                           data-toggle="tooltip" data-placement="top" href="#"
                        ><i class="fa fa-question-circle"></i></a>
                    </th>
                    <th>
                        # Under Replicated
                        <a title="Number of partition replicas that are not in sync with the primary partition"
                           data-toggle="tooltip" data-placement="top" href="#"
                        ><i class="fa fa-question-circle"></i></a>
                    </th>
                    <th>Custom Config?</th>
                    <#--<th>Consumers</th>-->
                </tr>
                </thead>
                <tbody>
                <#if topics?size == 0>
                <tr>
                    <td colspan="5">No topics available</td>
                </tr>
                </#if>
                <#list topics as t>
                <tr class="dataRow">
                    <td><a href="/topic/${t.name}">${t.name}</a></td>
                    <td>${t.partitions?size}</td>
                    <td <#if t.preferredReplicaPercent lt 1.0>class="warning"</#if>>${t.preferredReplicaPercent?string.percent}</td>
                    <td <#if t.underReplicatedPartitions?size gt 0>class="warning"</#if>>${t.underReplicatedPartitions?size}</td>
                    <td><@template.yn t.config?size gt 0/></td>
                    <#--<td>${t.consumers![]?size}</td>-->
                </tr>
                </#list>
                </tbody>
            </table>
        </div>
    </div>

<@template.footer/>

<script>
    $(document).ready(function() {
        $('#filter').focus();

    <#if filter??>
        $('#filter').val('${filter}');
    </#if>
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>

src/main/resources/templates/consumer-detail.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Consumer: ${consumer.groupId}"/>

<#setting number_format="0">

<h1>Kafka Consumer: ${consumer.groupId}</h1>

<div id="overview">
    <h2>Overview</h2>
    <table class="table table-bordered overview">
        <tbody>
        <tr>
            <td>Active Instances</td>
            <td>${consumer.activeInstances?size}</td>
        </tr>
        <tr>
            <td>Topics</td>
            <td>${consumer.topics?size}</td>
        </tr>
        <tr>
            <td>Active Topics</td>
            <td>${consumer.activeTopicCount}</td>
        </tr>
        </tbody>
    </table>
</div>

<div id="topics">
<#list consumer.topics as consumerTopic>
    <#assign tableId='topic-${consumerTopic_index}-table'>
    <h2><@template.toggleLink target="#${tableId}" anchor='${tableId}' /> Topic: <a href="/topic/${consumerTopic.topic}">${consumerTopic.topic}</a></h2>
    <div id="${tableId}">
        <p>
            <table class="table table-bordered overview">
                <tbody>
                    <tr>
                        <td>Total Threads</td>
                        <td>${consumerTopic.ownerCount}</td>
                    </tr>
                    <tr>
                        <td>Partition Coverage</td>
                        <td>${consumerTopic.coveragePercent * 100.0}%
                            (${consumerTopic.assignedPartitionCount} of ${consumerTopic.partitions?size})</td>
                    </tr>
                    <tr>
                        <td>Total Lag</td>
                        <td>${consumerTopic.lag}</td>
                    </tr>
                    <tr>
                        <td>Max Lag</td>
                        <td>${consumerTopic.maxLag}</td>
                    </tr>
                </tbody>
            </table>
        </p>
        <p>
            <table class="table table-bordered table-condensed">
                <thead>
                <tr>
                    <th>Partition</th>
                    <th>First Offset</th>
                    <th>Last Offset</th>
                    <th>Offset</th>
                    <th>Lag</th>
                    <th>Owner</th>
                </tr>
                </thead>
                <tbody>
                <#list consumerTopic.partitions as p>
                   <tr>
                       <td>${p.partitionId}</td>
                       <td>${p.firstOffset}</td>
                       <td>${p.size}</td>
                       <td>${p.offset}</td>
                       <td>${p.lag}</td>
                       <td>${p.owner!''}</td>
                   </tr>
                </#list>
                </tbody>
            </table>
        </p>
    </div>
</#list>

</div>

<@template.footer/>

src/main/resources/templates/not-initialized.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Initializing...">
   <meta http-equiv="refresh" content="5" >
</@template.header>

<div>
    <p>Internal caches are still initializing. Please wait...</p>
</div>

<@template.footer/>

src/main/resources/templates/topic-detail.ftl
<#--
 Copyright 2016 HomeAdvisor, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Topic: ${topic.name}">
  <style type="text/css">
      #action-bar { margin-top: 17px; }
      th { word-break: break-all; }
  </style>
</@template.header>

<#setting number_format="0">

<h1>Topic: ${topic.name}</h1>

<div id="action-bar" class="container">
    <a class="btn btn-default" href="/topic/${topic.name}/messages"><i class="fa fa-eye"></i> View Messages</a>
</div>

<div class="container-fluid">
<div class="row">

<div id="topic-overview" class="col-md-5">
    <h2>Overview</h2>

    <table class="table table-bordered">
        <tbody>
        <tr>
            <td># of Partitions</td>
            <td>${topic.partitions?size}</td>
        </tr>
        <tr>
            <td>Preferred Replicas</td>
            <td <#if topic.preferredReplicaPercent lt 1.0>class="warning"</#if>>${topic.preferredReplicaPercent?string.percent}</td>
        </tr>
        <tr>
            <td>Under Replicated Partitions</td>
            <td <#if topic.underReplicatedPartitions?size gt 0>class="warning"</#if>>${topic.underReplicatedPartitions?size}</td>
        </tr>
        <tr>
            <td>Total Size</td>
            <td>${topic.totalSize}</td>
        </tr>
        <tr>
            <td>Total Available Messages</td>
            <td>${topic.availableSize}</td>
        </tr>
        </tbody>
    </table>
</div>


<div id="topic-config" class="col-md-7">
    <h2>Configuration</h2>

    <#if topic.config?size == 0>
    <div>No topic specific configuration</div>
    <#else>
    <table class="table table-bordered">
        <tbody>
        <#list topic.config?keys as c>
              <tr>
                  <td>${c}</td>
                  <td>${topic.config[c]}</td>
              </tr>
        </#list>
        </tbody>
    </table>
    </#if>
</div>

</div>

<div class="row">
<div id="partition-detail" class="col-md-5">
    <h2>Partition Detail</h2>
    <table id="partition-detail-table" class="table table-bordered table-condensed small">
        <thead>
        <tr>
            <th>Partition</th>
            <th>First Offset</th>
            <th>Last Offset</th>
            <th>Size</th>
            <th>Leader</th>
            <th>Replicas</th>
            <th>In Sync Replicas</th>
            <th>Preferred Leader?</th>
            <th>Under Replicated?</th>
        </tr>
        </thead>
        <tbody>
        <#list topic.partitions as p>
        <tr>
            <td>${p.id}</td>
            <td>${p.firstOffset}</td>
            <td>${p.size}</td>
            <td>${p.size - p.firstOffset}</td>
            <td <#if !(p.leader)??>class="warning"</#if>>${(p.leader.id)!"none"}</td>
            <td><#list p.replicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
            <td><#list p.inSyncReplicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
            <td <#if !p.leaderPreferred>class="warning"</#if>><@template.yn p.leaderPreferred/></td>
            <td <#if p.underReplicated>class="warning"</#if>><@template.yn p.underReplicated/></td>
        </tr>
        </#list>
        </tbody>
    </table>
</div>

<div id="consumers" class="col-md-7">
    <h2>Consumers</h2>
    <table id="consumers-table" class="table table-bordered table-condensed small">
        <thead>
        <tr>
            <th>Group Id</th>
            <th>Lag</th>
            <th>Active Instances</th>
        </tr>
        </thead>
        <tbody>
        <#list consumers![] as c>
            <tr>
                <td><a href="/consumer/${c.groupId}">${c.groupId}</a></td>
                <td>${c.getTopic(topic.name).lag}</td>
                <td>
                    <ul class="list-unstyled">
                   <#list c.getActiveInstancesForTopic(topic.name) as i>
                       <li>${i.id}</li>
                   </#list>
                    </ul>
                </td>
            </tr>
        </#list>
        </tbody>
    </table>
</div>
</div>
</div>
<@template.footer/>